#!/bin/bash

cd $HOME/fielddbworkspace/CorpusWebService
bash switch_to_producti.sh 

$HOME/fielddbworkspace/CorpusWebService/node_modules/forever/bin/forever \
start \
-al $HOME/fielddbworkspace/logs/fielddbcorpus.log \
-ao $HOME/fielddbworkspace/logs/fielddbcorpusout.log \
-ae $HOME/fielddbworkspace/logs/fielddbcorpuserr.log \
bin/onlycouchdb.js localhost 3186
